env: "local"
storage_path: "postgresql://rosatom:rosatom@localhost:5432/telephone?sslmode=disable" # TODO : указать строку соединения 
logger : "pretty"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
clients:
  sso:
    address: "localhost:44044"
    timeout: 10h
    retries_count: 3